### PR TITLE
Add DaeMeshGeometry, StlMeshGeometry and abstract class MeshGeometry

### PR DESCRIPTION
**Pull request by wxmerkt**
Goes along with https://github.com/rdeits/meshcat/pull/48

TODO:
- [x] Get https://github.com/rdeits/meshcat/pull/48 reviewed and merged
- [x] Update `meshcat` submodule
- [ ] New `meshcat-python` pip release

### CODE REVIEW

**Comment by rdeits** [comment]
This also looks great, thanks again!

Do you have any example STL and DAE meshes we can include as test cases?

**Comment by wxmerkt** [comment]
I've updated the meshcat submodule and added a note to the demo that DAE and STL could be loaded as well. I did not add any meshes directly.

**Comment by wxmerkt** [comment]
@rdeits Is this good to merge?

**Comment by rdeits** [comment]
I'm trying to add test meshes to make sure this works. The STL loader looks good, but my naive attempt to generate a DAE mesh with meshlab isn't loading yet. I'll merge this as soon as I've got the new tests passing.

**Comment by rdeits** [comment]
Ok, this is now merged and available on pip in meshcat v0.0.14

**Comment by wxmerkt** [comment]
Thank you, Robin! :-)

**Pull request merged**
