### PR TITLE
add text, circle, ring geometry

### PR DESCRIPTION
**Pull request by shensquared**
the `Ring` and `Circle` geometries were added back in summer and they do load successfully. The new `Text` is just mimicking that modification.

### CODE REVIEW

**Comment by rdeits** [comment]
Cool! Is this still giving the same error you mentioned in #28 ?

**Comment by shensquared** [comment]
yes, this is what's giving me the missing uuid error

**Comment by rdeits** [comment]
What's the full error message?

**Comment by shensquared** [comment]
close this PR as we are attempting a different approach in https://github.com/rdeits/meshcat/pull/43

**Comment by gnthibault** [comment]
@shensquared  sorry to bring this again, but where can I find examples of how to use either text, circles or plane in meshcat python ? Is there a generic class that can be used to create those geometries ?

**Pull request closed without merging**
