### PR TITLE
ioloop.install() no longer necessary for pyzmq >= 17

### LINKED ISSUE #52: zmqserver.py:27: DeprecationWarning: zmq.eventloop.ioloop is deprecated
My mac CI canary just caught a new deprecation on mac:
```
/private/var/tmp/_bazel_runner/b24c2514e71e3bad206757e8aeba7ff5/sandbox/darwin-sandbox/285/execroot/underactuated/bazel-out/darwin-fastbuild/bin/underactuated/quadrotor/lqr.runfiles/drake/.lib/python3.7/site-packages/meshcat/servers/zmqserver.py:27: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  ioloop.install()
```

### PR DESCRIPTION
**Pull request by rdeits**
Resolves #52

### CODE REVIEW

**Comment by rdeits** [comment]
Weird that travis-CI isn't reporting status here, but it's green: https://travis-ci.org/github/rdeits/meshcat-python/builds/680375559

**Comment by EricCousineau-TRI** [comment]
Unfortunately, this breaks Drake due to it using `python3-zmq` (16.0.2) from Bionic:
https://github.com/RobotLocomotion/drake/pull/13155
https://drake-cdash.csail.mit.edu/testDetails.php?test=37559421&build=1287215

I've confirmed that reverting this single commit enables the Drake tests to pass.

Is it possible to revert this commit and keep the vestigial part in there? Or do a small version check?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI Can you open a PR with the version check guard on the looper install statement?  That way, we'll know for sure that its compatible with Drake instead of asking rdeits to test it for us.

**Comment by EricCousineau-TRI** [comment]
Yup, will do!

**Comment by EricCousineau-TRI** [comment]
Filed: https://github.com/rdeits/meshcat-python/pull/58
Will update Drake PR.

**Pull request merged**
